image: nixos/nix

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  cache: {}
  stage: test
  script:
  - export NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs/archive/19.09.tar.gz"
  - make build
  artifacts:
    paths:
    - public
  only:
  - master

pages:
  cache: {}
  stage: deploy
  script:
  - export NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs/archive/19.09.tar.gz"
  - make build
  artifacts:
    paths:
    - public
  only:
  - tags
