languageCode = "en-us"
theme = "hello-friend-ng"

title = "MadrHacks"
baseURL = "http://madrhacks.org/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "a lodge of Ethical Hackers"
  keywords = "blog, hacking"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  customCSS = ["/css/custom.css"]
  customJS = ["/js/logo-switcher.js"]

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  [params.logo]
    logoText = "MadrHacks"
    logoHomeLink = "/"
    [params.logo.light]
      brandPath = "/svg/logo-green.svg"
      path = "/svg/logo-m-green.svg"
    [params.logo.dark]
      brandPath = "/svg/logo-white.svg"
      path = "/svg/logo-m-white.svg"

[languages]
  [languages.en]
    title = "MadrHacks"
    subtitle = "A lodge of Ethical Hackers"
    homeSubtitle = "A lodge of Ethical Hackers"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
