title = "MadrHacks"
baseURL = "https://www.madrhacks.org"

theme = "madrhacks"


languageCode = "en-us"
DefaultContentLanguage = "en"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
  tag      = "tags"
  category = "categories"
  author   = "authors"

[params]
  dateFormat  = "2 January, 2006"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "a lodge of Ethical Hackers"
  keywords = "blog, hacking"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  customCSS = ["/css/custom.css"]

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  [params.logo]
    logoText = "MadrHacks"
    logoHomeLink = "/"
    [params.logo.light]
      brandPath = "/svg/logo-green.svg"
      path = "/svg/logo-m-green.svg"
    [params.logo.dark]
      brandPath = "/svg/logo-green.svg"
      path = "/svg/logo-m-green.svg"

[languages]
  [languages.en]
    title = "MadrHacks"
    subtitle = "A lodge of Ethical Hackers"
    homeSubtitle = "A lodge of Ethical Hackers"
    keywords = "Block, Hackers, CTF"
    readOtherPosts = "Read other posts"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "writeups"
    name       = "Writeups"
    url        = "/writeups"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "resource"
    name       = "Resources"
    url        = "/resource"
